qcacld-3.0: Fix non-debug build after LA.UM.7.11.r1-04800-NICOBAR.0
Missing WLAN_DEBUG.

/mnt/ssd/kernels/grus/drivers/staging/qcacld-3.0/core/sap/src/sap_module.c:1320:5: error: implicit declaration of function 'sap_get_csa_reason_str' [-Werror,-Wimplicit-function-declaration]
                         sap_get_csa_reason_str(sapContext->csa_reason),
                         ^
1 error generated.

/mnt/ssd/kernels/grus/drivers/staging/qcacld-3.0/core/wma/src/wma_mgmt.c:3205:5: error: implicit declaration of function 'wma_get_status_str' [-Werror,-Wimplicit-function-declaration]
                  wma_get_status_str(status), desc_id);
                  ^
/mnt/ssd/kernels/grus/drivers/staging/qcacld-3.0/core/wma/src/wma_mgmt.c:3205:5: note: did you mean 'wma_get_stats_req'?
/mnt/ssd/kernels/grus/drivers/staging/qcacld-3.0/core/wma/inc/wma_internal.h:981:6: note: 'wma_get_stats_req' declared here
void wma_get_stats_req(WMA_HANDLE handle,
     ^
1 error generated.

Signed-off-by: Albert I <kras@raphielgang.org>